# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

p_betweensumofsquare <- function(solution, data) {
    .Call('_rgeoda_p_betweensumofsquare', PACKAGE = 'rgeoda', solution, data)
}

p_totalsumofsquare <- function(data) {
    .Call('_rgeoda_p_totalsumofsquare', PACKAGE = 'rgeoda', data)
}

p_withinsumofsquare <- function(solution, data) {
    .Call('_rgeoda_p_withinsumofsquare', PACKAGE = 'rgeoda', solution, data)
}

p_skater <- function(k, xp_w, data, distance_method, bound_vals, min_bound, seed, cpu_threads) {
    .Call('_rgeoda_p_skater', PACKAGE = 'rgeoda', k, xp_w, data, distance_method, bound_vals, min_bound, seed, cpu_threads)
}

p_redcap <- function(k, xp_w, data, redcap_method, distance_method, bound_vals, min_bound, seed, cpu_threads) {
    .Call('_rgeoda_p_redcap', PACKAGE = 'rgeoda', k, xp_w, data, redcap_method, distance_method, bound_vals, min_bound, seed, cpu_threads)
}

p_schc <- function(k, xp_w, data, linkage_method, distance_method, bound_vals, min_bound) {
    .Call('_rgeoda_p_schc', PACKAGE = 'rgeoda', k, xp_w, data, linkage_method, distance_method, bound_vals, min_bound)
}

p_maxp_greedy <- function(xp_w, data, bound_vals, min_bound, iterations, init_regions, distance_method, seed, cpu_threads) {
    .Call('_rgeoda_p_maxp_greedy', PACKAGE = 'rgeoda', xp_w, data, bound_vals, min_bound, iterations, init_regions, distance_method, seed, cpu_threads)
}

p_maxp_sa <- function(xp_w, data, bound_vals, min_bound, iterations, cooling_rate, sa_maxit, init_regions, distance_method, seed, cpu_threads) {
    .Call('_rgeoda_p_maxp_sa', PACKAGE = 'rgeoda', xp_w, data, bound_vals, min_bound, iterations, cooling_rate, sa_maxit, init_regions, distance_method, seed, cpu_threads)
}

p_maxp_tabu <- function(xp_w, data, bound_vals, min_bound, iterations, tabu_length, conv_tabu, init_regions, distance_method, seed, cpu_threads) {
    .Call('_rgeoda_p_maxp_tabu', PACKAGE = 'rgeoda', xp_w, data, bound_vals, min_bound, iterations, tabu_length, conv_tabu, init_regions, distance_method, seed, cpu_threads)
}

p_azp_greedy <- function(p, xp_w, data, bound_vals, min_bound, inits, init_regions, distance_method, seed) {
    .Call('_rgeoda_p_azp_greedy', PACKAGE = 'rgeoda', p, xp_w, data, bound_vals, min_bound, inits, init_regions, distance_method, seed)
}

p_azp_sa <- function(p, xp_w, data, cooling_rate, sa_maxit, bound_vals, min_bound, inits, init_regions, distance_method, seed) {
    .Call('_rgeoda_p_azp_sa', PACKAGE = 'rgeoda', p, xp_w, data, cooling_rate, sa_maxit, bound_vals, min_bound, inits, init_regions, distance_method, seed)
}

p_azp_tabu <- function(p, xp_w, data, tabu_length, conv_tabu, bound_vals, min_bound, inits, init_regions, distance_method, seed) {
    .Call('_rgeoda_p_azp_tabu', PACKAGE = 'rgeoda', p, xp_w, data, tabu_length, conv_tabu, bound_vals, min_bound, inits, init_regions, distance_method, seed)
}

p_LISA__Run <- function(xp) {
    invisible(.Call('_rgeoda_p_LISA__Run', PACKAGE = 'rgeoda', xp))
}

p_LISA__SetNumPermutations <- function(xp, num_perm) {
    invisible(.Call('_rgeoda_p_LISA__SetNumPermutations', PACKAGE = 'rgeoda', xp, num_perm))
}

p_LISA__SetNumThreads <- function(xp, num_threads) {
    invisible(.Call('_rgeoda_p_LISA__SetNumThreads', PACKAGE = 'rgeoda', xp, num_threads))
}

p_LISA__GetLISAValues <- function(xp) {
    .Call('_rgeoda_p_LISA__GetLISAValues', PACKAGE = 'rgeoda', xp)
}

p_LISA__GetLocalSignificanceValues <- function(xp) {
    .Call('_rgeoda_p_LISA__GetLocalSignificanceValues', PACKAGE = 'rgeoda', xp)
}

p_LISA__GetClusterIndicators <- function(xp) {
    .Call('_rgeoda_p_LISA__GetClusterIndicators', PACKAGE = 'rgeoda', xp)
}

p_LISA__GetNumNeighbors <- function(xp) {
    .Call('_rgeoda_p_LISA__GetNumNeighbors', PACKAGE = 'rgeoda', xp)
}

p_LISA__SetSignificanceCutoff <- function(xp, cutoff) {
    invisible(.Call('_rgeoda_p_LISA__SetSignificanceCutoff', PACKAGE = 'rgeoda', xp, cutoff))
}

p_LISA__GetLabels <- function(xp) {
    .Call('_rgeoda_p_LISA__GetLabels', PACKAGE = 'rgeoda', xp)
}

p_LISA__GetColors <- function(xp) {
    .Call('_rgeoda_p_LISA__GetColors', PACKAGE = 'rgeoda', xp)
}

p_LISA__GetBO <- function(xp, pval) {
    .Call('_rgeoda_p_LISA__GetBO', PACKAGE = 'rgeoda', xp, pval)
}

p_LISA__GetFDR <- function(xp, pval) {
    .Call('_rgeoda_p_LISA__GetFDR', PACKAGE = 'rgeoda', xp, pval)
}

p_localmoran <- function(xp_w, data, permutations, significance_cutoff, cpu_threads, seed) {
    .Call('_rgeoda_p_localmoran', PACKAGE = 'rgeoda', xp_w, data, permutations, significance_cutoff, cpu_threads, seed)
}

p_localgeary <- function(xp_w, data, permutations, significance_cutoff, cpu_threads, seed) {
    .Call('_rgeoda_p_localgeary', PACKAGE = 'rgeoda', xp_w, data, permutations, significance_cutoff, cpu_threads, seed)
}

p_localmultigeary <- function(xp_w, data, permutations, significance_cutoff, cpu_threads, seed) {
    .Call('_rgeoda_p_localmultigeary', PACKAGE = 'rgeoda', xp_w, data, permutations, significance_cutoff, cpu_threads, seed)
}

p_localg <- function(xp_w, data, permutations, significance_cutoff, cpu_threads, seed) {
    .Call('_rgeoda_p_localg', PACKAGE = 'rgeoda', xp_w, data, permutations, significance_cutoff, cpu_threads, seed)
}

p_localgstar <- function(xp_w, data, permutations, significance_cutoff, cpu_threads, seed) {
    .Call('_rgeoda_p_localgstar', PACKAGE = 'rgeoda', xp_w, data, permutations, significance_cutoff, cpu_threads, seed)
}

p_localjoincount <- function(xp_w, data, permutations, significance_cutoff, cpu_threads, seed) {
    .Call('_rgeoda_p_localjoincount', PACKAGE = 'rgeoda', xp_w, data, permutations, significance_cutoff, cpu_threads, seed)
}

p_localmultijoincount <- function(xp_w, data, permutations, significance_cutoff, cpu_threads, seed) {
    .Call('_rgeoda_p_localmultijoincount', PACKAGE = 'rgeoda', xp_w, data, permutations, significance_cutoff, cpu_threads, seed)
}

p_quantilelisa <- function(xp_w, k, quantile, data, permutations, significance_cutoff, cpu_threads, seed) {
    .Call('_rgeoda_p_quantilelisa', PACKAGE = 'rgeoda', xp_w, k, quantile, data, permutations, significance_cutoff, cpu_threads, seed)
}

p_multiquantilelisa <- function(xp_w, k_s, q_s, data_s, permutations, significance_cutoff, cpu_threads, seed) {
    .Call('_rgeoda_p_multiquantilelisa', PACKAGE = 'rgeoda', xp_w, k_s, q_s, data_s, permutations, significance_cutoff, cpu_threads, seed)
}

p_GeoDa__new <- function(file_path) {
    .Call('_rgeoda_p_GeoDa__new', PACKAGE = 'rgeoda', file_path)
}

p_GeoDa__new1 <- function(layer_name, map_type, num_features, wkbs, wkb_bytes_len) {
    .Call('_rgeoda_p_GeoDa__new1', PACKAGE = 'rgeoda', layer_name, map_type, num_features, wkbs, wkb_bytes_len)
}

p_GeoDa__GetNumObs <- function(xp) {
    .Call('_rgeoda_p_GeoDa__GetNumObs', PACKAGE = 'rgeoda', xp)
}

p_GeoDa__GetNumCols <- function(xp) {
    .Call('_rgeoda_p_GeoDa__GetNumCols', PACKAGE = 'rgeoda', xp)
}

p_GeoDa__GetMapType <- function(xp) {
    .Call('_rgeoda_p_GeoDa__GetMapType', PACKAGE = 'rgeoda', xp)
}

p_GeoDa__GetFieldNames <- function(xp) {
    .Call('_rgeoda_p_GeoDa__GetFieldNames', PACKAGE = 'rgeoda', xp)
}

p_GeoDa__GetFieldTypes <- function(xp) {
    .Call('_rgeoda_p_GeoDa__GetFieldTypes', PACKAGE = 'rgeoda', xp)
}

p_GeoDa__GetNumericCol <- function(xp, col_name) {
    .Call('_rgeoda_p_GeoDa__GetNumericCol', PACKAGE = 'rgeoda', xp, col_name)
}

p_GeoDa__GetIntegerCol <- function(xp, col_name) {
    .Call('_rgeoda_p_GeoDa__GetIntegerCol', PACKAGE = 'rgeoda', xp, col_name)
}

p_GeoDa__GetStringCol <- function(xp, col_name) {
    .Call('_rgeoda_p_GeoDa__GetStringCol', PACKAGE = 'rgeoda', xp, col_name)
}

p_GeoDa__GetNullValues <- function(xp, col_name) {
    .Call('_rgeoda_p_GeoDa__GetNullValues', PACKAGE = 'rgeoda', xp, col_name)
}

p_GeoDa__GetPointer <- function(xp) {
    .Call('_rgeoda_p_GeoDa__GetPointer', PACKAGE = 'rgeoda', xp)
}

p_gda_demean <- function(data) {
    .Call('_rgeoda_p_gda_demean', PACKAGE = 'rgeoda', data)
}

p_gda_standardize <- function(data) {
    .Call('_rgeoda_p_gda_standardize', PACKAGE = 'rgeoda', data)
}

p_gda_mad <- function(data) {
    .Call('_rgeoda_p_gda_mad', PACKAGE = 'rgeoda', data)
}

p_naturalbreaks <- function(k, data) {
    .Call('_rgeoda_p_naturalbreaks', PACKAGE = 'rgeoda', k, data)
}

p_quantilebreaks <- function(k, data) {
    .Call('_rgeoda_p_quantilebreaks', PACKAGE = 'rgeoda', k, data)
}

p_hinge15breaks <- function(data) {
    .Call('_rgeoda_p_hinge15breaks', PACKAGE = 'rgeoda', data)
}

p_hinge30breaks <- function(data) {
    .Call('_rgeoda_p_hinge30breaks', PACKAGE = 'rgeoda', data)
}

p_percentilebreaks <- function(data) {
    .Call('_rgeoda_p_percentilebreaks', PACKAGE = 'rgeoda', data)
}

p_stddevbreaks <- function(data) {
    .Call('_rgeoda_p_stddevbreaks', PACKAGE = 'rgeoda', data)
}

p_GeoDaWeight__GetPointer <- function(xp) {
    .Call('_rgeoda_p_GeoDaWeight__GetPointer', PACKAGE = 'rgeoda', xp)
}

p_GeoDaWeight__GetNumObs <- function(xp) {
    .Call('_rgeoda_p_GeoDaWeight__GetNumObs', PACKAGE = 'rgeoda', xp)
}

p_GeoDaWeight__IsSymmetric <- function(xp) {
    .Call('_rgeoda_p_GeoDaWeight__IsSymmetric', PACKAGE = 'rgeoda', xp)
}

p_GeoDaWeight__HasIsolations <- function(xp) {
    .Call('_rgeoda_p_GeoDaWeight__HasIsolations', PACKAGE = 'rgeoda', xp)
}

p_GeoDaWeight__GetSparsity <- function(xp) {
    .Call('_rgeoda_p_GeoDaWeight__GetSparsity', PACKAGE = 'rgeoda', xp)
}

p_GeoDaWeight__GetDensity <- function(xp) {
    .Call('_rgeoda_p_GeoDaWeight__GetDensity', PACKAGE = 'rgeoda', xp)
}

p_GeoDaWeight__GetMinNeighbors <- function(xp) {
    .Call('_rgeoda_p_GeoDaWeight__GetMinNeighbors', PACKAGE = 'rgeoda', xp)
}

p_GeoDaWeight__GetMaxNeighbors <- function(xp) {
    .Call('_rgeoda_p_GeoDaWeight__GetMaxNeighbors', PACKAGE = 'rgeoda', xp)
}

p_GeoDaWeight__GetMeanNeighbors <- function(xp) {
    .Call('_rgeoda_p_GeoDaWeight__GetMeanNeighbors', PACKAGE = 'rgeoda', xp)
}

p_GeoDaWeight__GetMedianNeighbors <- function(xp) {
    .Call('_rgeoda_p_GeoDaWeight__GetMedianNeighbors', PACKAGE = 'rgeoda', xp)
}

p_GeoDaWeight__SpatialLag <- function(xp, obs_idx, vals) {
    .Call('_rgeoda_p_GeoDaWeight__SpatialLag', PACKAGE = 'rgeoda', xp, obs_idx, vals)
}

p_GeoDaWeight__GetNeighborSize <- function(xp, obs_idx) {
    .Call('_rgeoda_p_GeoDaWeight__GetNeighborSize', PACKAGE = 'rgeoda', xp, obs_idx)
}

p_GeoDaWeight__SaveToFile <- function(xp, out_path, layer_name, id_name, id_vec) {
    .Call('_rgeoda_p_GeoDaWeight__SaveToFile', PACKAGE = 'rgeoda', xp, out_path, layer_name, id_name, id_vec)
}

p_GeoDaWeight__GetNeighbors <- function(xp, obs_idx) {
    .Call('_rgeoda_p_GeoDaWeight__GetNeighbors', PACKAGE = 'rgeoda', xp, obs_idx)
}

p_GeoDaWeight__GetNeighborWeights <- function(xp, obs_idx) {
    .Call('_rgeoda_p_GeoDaWeight__GetNeighborWeights', PACKAGE = 'rgeoda', xp, obs_idx)
}

p_gda_min_distthreshold <- function(xp_geoda, is_arc, is_mile) {
    .Call('_rgeoda_p_gda_min_distthreshold', PACKAGE = 'rgeoda', xp_geoda, is_arc, is_mile)
}

p_gda_queen_weights <- function(xp_geoda, order, include_lower_order, precision_threshold) {
    .Call('_rgeoda_p_gda_queen_weights', PACKAGE = 'rgeoda', xp_geoda, order, include_lower_order, precision_threshold)
}

p_gda_rook_weights <- function(xp_geoda, order, include_lower_order, precision_threshold) {
    .Call('_rgeoda_p_gda_rook_weights', PACKAGE = 'rgeoda', xp_geoda, order, include_lower_order, precision_threshold)
}

p_gda_distance_weights <- function(xp_geoda, dist_thres, power, is_inverse, is_arc, is_mile) {
    .Call('_rgeoda_p_gda_distance_weights', PACKAGE = 'rgeoda', xp_geoda, dist_thres, power, is_inverse, is_arc, is_mile)
}

p_gda_kernel_weights <- function(xp_geoda, bandwidth, kernel_method, use_kernel_diagonals, power, is_inverse, is_arc, is_mile) {
    .Call('_rgeoda_p_gda_kernel_weights', PACKAGE = 'rgeoda', xp_geoda, bandwidth, kernel_method, use_kernel_diagonals, power, is_inverse, is_arc, is_mile)
}

p_gda_knn_weights <- function(xp_geoda, k, power, is_inverse, is_arc, is_mile) {
    .Call('_rgeoda_p_gda_knn_weights', PACKAGE = 'rgeoda', xp_geoda, k, power, is_inverse, is_arc, is_mile)
}

p_gda_kernel_knn_weights <- function(xp_geoda, k, power, is_inverse, is_arc, is_mile, kernel_method, bandwidth, adaptive_bandwidth, use_kernel_diagonals) {
    .Call('_rgeoda_p_gda_kernel_knn_weights', PACKAGE = 'rgeoda', xp_geoda, k, power, is_inverse, is_arc, is_mile, kernel_method, bandwidth, adaptive_bandwidth, use_kernel_diagonals)
}

